"""initial

Revision ID: abd3ef6f8dee
Revises: 
Create Date: 2022-12-25 07:30:57.387988

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app


# revision identifiers, used by Alembic.
revision = 'abd3ef6f8dee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', app.models.client.GUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cpu_load',
    sa.Column('id', app.models.client.GUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('load', sa.FLOAT(), nullable=True),
    sa.Column('client_id', app.models.client.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cpu_load')
    op.drop_table('client')
    # ### end Alembic commands ###
